[2023-12-22T09:19:09.761+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dd_mssql_snapshot.prepare_query_statement manual__2023-12-22T09:12:30.494042+00:00 [queued]>
[2023-12-22T09:19:09.768+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dd_mssql_snapshot.prepare_query_statement manual__2023-12-22T09:12:30.494042+00:00 [queued]>
[2023-12-22T09:19:09.768+0000] {taskinstance.py:1361} INFO - Starting attempt 7 of 8
[2023-12-22T09:19:09.775+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): prepare_query_statement> on 2023-12-22 09:12:30.494042+00:00
[2023-12-22T09:19:09.779+0000] {standard_task_runner.py:57} INFO - Started process 307 to run task
[2023-12-22T09:19:09.783+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dd_mssql_snapshot', 'prepare_query_statement', 'manual__2023-12-22T09:12:30.494042+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/snapshot-json.py', '--cfg-path', '/tmp/tmp_2kz7uov']
[2023-12-22T09:19:09.784+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask prepare_query_statement
[2023-12-22T09:19:09.831+0000] {task_command.py:416} INFO - Running <TaskInstance: dd_mssql_snapshot.prepare_query_statement manual__2023-12-22T09:12:30.494042+00:00 [running]> on host 90263e0a625e
[2023-12-22T09:19:09.898+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dd_mssql_snapshot' AIRFLOW_CTX_TASK_ID='prepare_query_statement' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T09:12:30.494042+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-22T09:12:30.494042+00:00'
[2023-12-22T09:19:09.899+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/snapshot-json.py", line 76, in prepare_query_statement
    athena_previous_hour = generate_date_strings()
NameError: name 'generate_date_strings' is not defined
[2023-12-22T09:19:09.911+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dd_mssql_snapshot, task_id=prepare_query_statement, execution_date=20231222T091230, start_date=20231222T091909, end_date=20231222T091909
[2023-12-22T09:19:09.927+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task prepare_query_statement (name 'generate_date_strings' is not defined; 307)
[2023-12-22T09:19:09.960+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-22T09:19:09.976+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
