[2024-05-05T01:18:52.135+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_transaction_analysis.select_features manual__2024-05-05T01:16:42.876728+00:00 [queued]>
[2024-05-05T01:18:52.144+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_transaction_analysis.select_features manual__2024-05-05T01:16:42.876728+00:00 [queued]>
[2024-05-05T01:18:52.145+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-05T01:18:52.155+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): select_features> on 2024-05-05 01:16:42.876728+00:00
[2024-05-05T01:18:52.162+0000] {standard_task_runner.py:57} INFO - Started process 138 to run task
[2024-05-05T01:18:52.168+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_transaction_analysis', 'select_features', 'manual__2024-05-05T01:16:42.876728+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/bitcoin.py', '--cfg-path', '/tmp/tmp0gehtn6q']
[2024-05-05T01:18:52.173+0000] {standard_task_runner.py:85} INFO - Job 204: Subtask select_features
[2024-05-05T01:18:52.234+0000] {task_command.py:416} INFO - Running <TaskInstance: bitcoin_transaction_analysis.select_features manual__2024-05-05T01:16:42.876728+00:00 [running]> on host c967b8493ef9
[2024-05-05T01:18:52.327+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_transaction_analysis' AIRFLOW_CTX_TASK_ID='select_features' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T01:16:42.876728+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T01:16:42.876728+00:00'
[2024-05-05T01:18:57.645+0000] {logging_mixin.py:154} INFO - Datasets split into training and prediction sets.
[2024-05-05T01:18:57.647+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bitcoin.py", line 104, in select_features
    df_training = pd.read_csv(path_training)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/datasets/training_dataset.csv'
[2024-05-05T01:18:57.667+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bitcoin_transaction_analysis, task_id=select_features, execution_date=20240505T011642, start_date=20240505T011852, end_date=20240505T011857
[2024-05-05T01:18:57.680+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 204 for task select_features ([Errno 2] No such file or directory: '/opt/airflow/dags/datasets/training_dataset.csv'; 138)
[2024-05-05T01:18:57.700+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-05T01:18:57.725+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
